name: matchito
description: Code generation for matchito mocktail mocks.
version: 0.0.1
repository: https://github.com/jtdLab/matchito
issue_tracker: https://github.com/jtdLab/matchito/issues
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  matchito_annotation:
    path: ../matchito_annotation
  source_gen: ^4.0.2

dev_dependencies:
  source_gen_test: ^1.3.2
  test: ^1.27.0
